slam_toolbox:
  ros__parameters:
    use_sim_time: false

    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0

    transform_timeout: 0.3
    tf_buffer_duration: 60.0

    publish_tf: true
    mode: mapping